version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
     - "8080:80"
    depends_on:
      - app
    volumes:
      - ./phabulous.conf:/etc/nginx/conf.d/default.conf

  app:
    image: phabulous
    build:
      context: .
      dockerfile: Dockerfile.php
